#!/usr/bin/env node
/**
 * Compiles `content/posts/*.mdoc` into a plain TypeScript module.
 *
 * ── Why a build step instead of reading posts at request time ──────────────
 *
 * The CSP mints a nonce per response, which makes every route dynamic. A
 * reader that touched the filesystem would therefore run on every request —
 * and Cloudflare Workers have no filesystem, so the Cloudflare origin would
 * 500 on any blog page while Vercel served it happily. That is the worst class
 * of bug this architecture can produce: one that appears on only one origin.
 *
 * Compiling to a module removes the question. It also keeps Markdoc, Shiki,
 * and their grammars entirely out of the Worker bundle: they are
 * devDependencies that run here and never ship.
 *
 * ── Trust boundary ────────────────────────────────────────────────────────
 *
 * The HTML produced here is injected with `dangerouslySetInnerHTML`, so it is
 * passed through an enforced tag and attribute allowlist — see
 * `scripts/lib/markdoc-render.mjs`, which is unit-tested. "The content is
 * first-party" is deliberately NOT the control: that assumption stops holding
 * the moment posts are authored through a browser CMS session instead of a git
 * commit, and the allowlist is what keeps this correct when it does.
 */
import { readdir, readFile, writeFile, mkdir } from 'node:fs/promises'
import { join, basename } from 'node:path'
import Markdoc from '@markdoc/markdoc'
import { load as parseYaml } from 'js-yaml'
import { createHighlighter } from 'shiki'
import { renderNode } from './lib/markdoc-render.mjs'

const POSTS_DIR = 'content/posts'
const OUT_FILE = 'src/content/generated/posts.ts'

/**
 * Only these languages get grammars loaded. Shiki pulls one grammar per
 * language; loading everything it supports would add megabytes to the build
 * for no benefit.
 */
const LANGUAGES = [
  'bash', 'python', 'javascript', 'typescript', 'tsx', 'json',
  'yaml', 'sql', 'nginx', 'docker', 'http', 'diff', 'text',
]

const THEMES = { light: 'github-light', dark: 'github-dark' }

function readingMinutes(markdown) {
  const words = markdown.trim().split(/\s+/).filter(Boolean).length
  return Math.max(1, Math.round(words / 200))
}

async function main() {
  let files = []
  try {
    files = (await readdir(POSTS_DIR)).filter((f) => f.endsWith('.mdoc'))
  } catch {
    console.warn(`build-posts: no ${POSTS_DIR} directory yet — emitting an empty index.`)
  }

  const highlighter = await createHighlighter({
    themes: Object.values(THEMES),
    langs: LANGUAGES,
  })

  /*
   * Highlighting happens here, not in the browser. Shipping Shiki and every
   * grammar to the client to colour text that never changes after build would
   * be the single largest thing on the page.
   */
  const highlight = (code, language) =>
    highlighter.codeToHtml(code, {
      lang: LANGUAGES.includes(language) ? language : 'text',
      themes: THEMES,
      defaultColor: false,
    })

  const posts = []
  const warnings = []

  for (const file of files) {
    const raw = await readFile(join(POSTS_DIR, file), 'utf8')
    const ast = Markdoc.parse(raw)

    const frontmatter = ast.attributes.frontmatter
      ? parseYaml(ast.attributes.frontmatter)
      : {}

    for (const required of ['title', 'summary', 'publishedAt']) {
      if (!frontmatter[required]) {
        throw new Error(`${file}: missing required frontmatter field "${required}"`)
      }
    }

    const report = (message) => warnings.push(`${file}: ${message}`)

    /*
     * Markdoc wraps every document in an <article>. The post page already
     * provides one around the title and metadata, so keeping this would nest
     * two. Unwrapping at the source is cleaner than allowlisting an element we
     * do not want.
     */
    const transformed = Markdoc.transform(ast)
    const body =
      transformed && typeof transformed === 'object' && transformed.name === 'article'
        ? transformed.children
        : transformed

    const html = renderNode(body, highlight, report)

    posts.push({
      slug: frontmatter.slug ?? basename(file, '.mdoc'),
      title: String(frontmatter.title),
      summary: String(frontmatter.summary),
      publishedAt: new Date(frontmatter.publishedAt).toISOString(),
      updatedAt: frontmatter.updatedAt
        ? new Date(frontmatter.updatedAt).toISOString()
        : null,
      tags: Array.isArray(frontmatter.tags) ? frontmatter.tags.map(String) : [],
      draft: frontmatter.draft === true,
      readingMinutes: readingMinutes(raw),
      html,
    })
  }

  // Newest first, so no consumer has to repeat the comparator.
  posts.sort((a, b) => b.publishedAt.localeCompare(a.publishedAt))

  const banner =
    `// GENERATED by scripts/build-posts.mjs — do not edit.\n` +
    `// Source of truth is ${POSTS_DIR}/*.mdoc. Run \`npm run build:posts\`.\n\n` +
    `import type { Post } from '../post-types'\n\n`

  await mkdir('src/content/generated', { recursive: true })
  await writeFile(
    OUT_FILE,
    `${banner}export const POSTS: Post[] = ${JSON.stringify(posts, null, 2)}\n`,
    'utf8',
  )

  // Anything the allowlist dropped is surfaced rather than silently swallowed.
  for (const warning of warnings) console.warn(`build-posts: ${warning}`)

  const drafts = posts.filter((p) => p.draft).length
  console.log(
    `build-posts: ${posts.length} post(s) compiled` +
      (drafts ? `, ${drafts} draft(s) excluded in production` : '') +
      (warnings.length ? `, ${warnings.length} sanitiser warning(s)` : ''),
  )
}

main().catch((error) => {
  console.error(`build-posts failed: ${error.message}`)
  process.exit(1)
})
